const mongoose = require("mongoose");

//define a saved schema for the database
const saveSchema = new mongoose.Schema({
  creator_id: String,
  parent: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
});

// compile model from schema
module.exports = mongoose.model("save", saveSchema);
